version: "3.9"
services:
  front:
    image: roastbeefer/web-carrot-frontend:latest
    ports:
      - "8080:80"
  back:
    image: roastbeefer/web-carrot-backend:latest
    ports:
      - "8050:8050"